### ISSUE TITLE
StateVector entry ordering

### ISSUE THREAD

**Issue by yoursunny** [justincpresley/ndn-sync#1]
I'm reading the source code of **StateVector** type, and noticed two related issues.

## specification branch

[SVS spec revision 2021-12-15](https://named-data.github.io/StateVectorSync/Specification.html) states:

> Node names in the encoded version vector are ordered in [NDN canonical order](https://named-data.net/doc/NDN-packet-spec/0.3/name.html#canonical-order) to allow for Interest aggregation.

The entries are stored in a `entries map[string]uint64` where each key is the semi-canonical URI representation of the node name.
The encoding function is [for range loop](https://github.com/justincpresley/ndn-sync/blob/7d09a05bbb23339fe5783969e4b9aec7495802e0/pkg/svs/state_vector.go#L158) over this map, without specific ordering.

[Go language spec](https://go.dev/ref/spec#For_statements) states:

> The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next.

Hence, looping over the map would emit the entries in unspecified order.
It does not generate the name order as expected in SVS spec.

## production branch

Documentation states a difference is:

> StateVectors are ordered by Latest Entries.

In [OrderedMap](https://github.com/justincpresley/ndn-sync/blob/761a11526315147c98bf7abc611ff469629cc824/util/orderedmap/orderedmap.go#L66) type, the latest entry of a StateVector is at the front, not at the back.
Hence, the actual order is better described as "reverse latest entries" or "latest entry first" or "descending order of last update time".

I have concerns on how this changed ordering impacts the effectiveness of in-network Interest aggregation.
This should be explained in the library documentation.

**Comment by justincpresley** [comment]
Thank you for your observations.

Your points will be addressed in the following way. Please let me know if I misunderstood any concern or did not fully address a concern.
> [**summary**] Specification StateVectors do not follow NDN canonical order (required by the technical specification) due to Go maps not guaranteeing order.
* I have made note of this and will keep this issue open until this is fixed.

> [**summary**] The phrase "sorted by Latest Entries" is vague as it does not indicated descending/ascending behavior. This can be misunderstood to be ascending in update time.
* I have [corrected SVS's Readme](https://github.com/justincpresley/ndn-sync/blob/production/docs/syncs/SVS.md?plain=1#L35), but this will be made clearer moving forward.

> I have concerns on how this changed ordering impacts the effectiveness of in-network Interest aggregation.
* I also shared those concerns. While Scalability will be tackled with the changed ordering, I do have plans to re-introduce in-network Interest aggregation.
